name: joicrememory
description: "Mobile app for local social initiatives."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.13.1
  intl: ^0.20.2
  stream_chat_flutter: ^9.17.0
  geolocator: ^14.0.2
  shared_preferences: ^2.5.5
  pdf: ^3.12.0
  printing: ^5.14.3
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Medium.ttf
